use_frameworks!

platform :ios, '9.0'

target 'LoginModuleSDK_Example' do
  pod 'LoginModuleSDK', :path => '../'

  target 'LoginModuleSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
